import { test, expect } from '@playwright/test';

test('Login Demo 1', async ({ page }) => {

    await page.goto('https://demo.applitools.com/')
    await page.pause()
    await page.locator('[Placeholder="Enter your username"]').fill('Sunanda')
    await page.locator('[Placeholder="Enter your password"]').fill('1234')
    await page.locator('text=Sign in').click()

})
// we can run only one specific test by .only tag
test.only('Login Demo 2', async ({ page }) => {

    await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    // await page.pause()
    // await page.locator('[Placeholder="username"]').fill('Admin')
    // await page.locator('[Placeholder="password"]').fill('admin123')
    // await page.locator('[button[@name="Login"]').click()
  

// Generated by recording 
    await page.getByPlaceholder('username').click();
    await page.getByPlaceholder('username').fill('Admin');
    await page.getByPlaceholder('password').click();
    await page.getByPlaceholder('password').fill('admin123');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.locator('span').filter({ hasText: 'Paul Collings' }).locator('i').click();
    await page.getByRole('menuitem', { name: 'Logout' }).click();

})